import { IUserProfileTableHeaderProps } from '@/type/client/business/settings.type';

export const ConstUserProfile: IUserProfileTableHeaderProps[] = [
  {
    id: '1',
    full_name: 'Lydia Kylio',
    email: 'lydiakalio124@gmail.com',
    email_verified_date: '24/08/2025 13:23pm',
    phone_number: '08064565388',
    is_activated: true,
    created_by: 'System',
    created_date: new Date(),
  },
  {
    id: '21',
    full_name: 'Hannah Ahmad',
    email: 'hannah.ahmad@gmail.com',
    email_verified_date: '20/09/2025 09:15am',
    phone_number: '08188874664',
    is_activated: true,
    created_by: 'System',
    created_date: new Date(),
  },
  {
    id: '34',
    full_name: 'James Okeke',
    email: 'jamesokeke@gmail.com',
    email_verified_date: '07/07/2025 13:23pm',
    phone_number: '08078488588',
    is_activated: false,
    created_by: 'System',
    created_date: new Date(),
  },
  {
    id: '22',
    full_name: 'Paul Diongoli',
    email: 'pauldiongoli@gmail.com',
    email_verified_date: '12/09/2025 13:23pm',
    phone_number: '01-8384884',
    is_activated: true,
    created_by: 'System',
    created_date: new Date(),
  },
  {
    id: '43',
    full_name: 'Joseph Ibrahim',
    email: 'josephibrahim@gmail.com',
    email_verified_date: '12/09/2025 13:23pm',
    phone_number: '09074638291',
    is_activated: true,
    created_by: 'System',
    created_date: new Date(),
  },
  {
    id: '46',
    full_name: 'Ekundayo Oluwapelumi',
    email: 'ekundayooluwapelumi@gmail.com',
    email_verified_date: '12/09/2025 13:23pm',
    phone_number: '08185830931',
    is_activated: true,
    created_by: 'System',
    created_date: new Date(),
  },
  {
    id: '67',
    full_name: 'Simon Maduabuchi',
    email: 'simon_maduabuchi@gmail.com',
    email_verified_date: '12/09/2025 13:23pm',
    phone_number: '07074785943',
    is_activated: true,
    created_by: 'System',
    created_date: new Date(),
  },
  {
    id: '38',
    full_name: 'Adedayo Solomon',
    email: 'adedayo.solomon@gmail.com',
    email_verified_date: '12/09/2025 13:23:pm',
    phone_number: '018688833',
    is_activated: false,
    created_by: 'System',
    created_date: new Date(),
  },
  {
    id: '50',
    full_name: 'Uchenna Nnamani',
    email: 'uchenna.nnamani@gmail.com',
    email_verified_date: '12/09/2025 13:23pm',
    phone_number: '0907688482',
    is_activated: true,
    created_by: 'System',
    created_date: new Date(),
  },
];
