export enum AppNotificationTypeEnum {
  REGISTRATION = 'REGISTRATION',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_PLACED = 'ORDER_PLACED',
  NEW_MESSAGE = 'NEW_MESSAGE',
  PRODUCT_REVIEW = 'PRODUCT_REVIEW',
  PROMOTION = 'PROMOTION',
  PRICE_DROP = 'PRICE_DROP',
  SHIPPING_UPDATE = 'SHIPPING_UPDATE',
  SYSTEM = 'SYSTEM',
}

export enum NotificationTemplateTypeEnum {
  IN_APP = 'IN_APP',
  SMS = 'SMS',
  MAIL = 'MAIL',
  DATABASE = 'DATABASE',
  PUSH = 'PUSH',
}
