'use client';
import { ReactNode, useState } from 'react';
import { SessionProvider } from 'next-auth/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
//import type { Metadata } from 'next';
import { sfProRounded } from './fonts';
import './globals.css';
import LoaderWrapper from '@/components/custom/LoaderWrapper';
import { Toaster } from 'sonner';
import { ServerIndicator } from '@/components/custom/ServerIndicator';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());
  return (
    <html lang='en'>
      <body className={`${sfProRounded.variable} font-sans antialiased`}>
        <LoaderWrapper>
          <SessionProvider>
            <QueryClientProvider client={queryClient}>
              <ServerIndicator />
              {children}
              <Toaster position='top-right' />
            </QueryClientProvider>
          </SessionProvider>
        </LoaderWrapper>
      </body>
    </html>
  );
}
