'use client';
import { ReactNode, useState } from 'react';
import { SessionProvider } from 'next-auth/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
//import type { Metadata } from 'next';
import { sfProRounded } from './fonts';
//import { Nunito } from 'next/font/google';
import './globals.css';
import LoaderWrapper from '@/components/custom/LoaderWrapper';
import { Toaster } from 'sonner';
import { ServerIndicator } from '@/components/custom/ServerIndicator';
//import './assets/styles/fonts.css';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// const nunito = Nunito({
//   subsets: ['latin'],
//   style: 'normal',
//   preload: true,
//   weight: ['200', '300', '400', '500', '600', '700'], // adjust as needed
//   variable: '--font-nunito',
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());
  return (
    <html lang='en'>
      <body className={`${sfProRounded.variable} antialiased`}>
        <LoaderWrapper>
          <SessionProvider>
            <QueryClientProvider client={queryClient}>
              <ServerIndicator />
              {children}
              <Toaster position='top-right' />
            </QueryClientProvider>
          </SessionProvider>
        </LoaderWrapper>
      </body>
    </html>
  );
}
